POST http://localhost:3306/api/createDb/pets
###
POST http://localhost:3306/api/createDb/logs
###
POST http://localhost:3306/api/createDb/medications
###
POST http://localhost:3306/api/createDb/prescriptions